dist: trusty
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
cache:
  directories:
  - "node_modules"
before_install:
  - pip install --user codecov
install:
  - npm install
script:
  - npm run lint
  - npm test
after_success:
  - npm run coverage
  - ./scripts/merge-coverage-reports.sh
  - codecov --file coverage/lcov.info --disable search
